#' Save a PDF plot along with the name of the file used to create it.
#' @param filename Destination to save the plot. Must be a PDF.
#' @param plot GGplot object to save.
#' @param cleanup Remove backup of PDF generated by ExifTool
#' @param scriptname Optional override to the currently open Rstudio file, or for use in the case that Rstudioapi is not available.
#' @param ... Other arguments which are passed directly to ggplot2::ggsave
#'
#' @importFrom ggplot2 ggsave
#' @importFrom rstudioapi getSourceEditorContext
#' @importFrom glue glue
#' @export
ggsave <- function(filename, plot, cleanup = T, scriptname = NULL, ...){
  ggplot2::ggsave(filename, plot, ...)

  check_exiftool()

  if(rstudioapi::isAvailable() & is.null(scriptname)){
    path = rstudioapi::getSourceEditorContext()$path
    path_to_config = system.file("extdata", "pcsave.cfg", package = "ggsource", mustWork = T)
    system(glue("exiftool -config {path_to_config} -ScriptPath={path} {filename}"))
  } else if (!is.null(scriptname)){
    path = scriptname
    path_to_config = system.file("extdata", "pcsave.cfg", package = "ggsource", mustWork = T)
    system(glue("exiftool -config {path_to_config} -ScriptPath={path} {filename}"))
  } else {
    stop("It looks like you aren't using RStudio and you haven't provided a scriptname.\n\n I've saved your plot, but haven't included the filename in it. See the documentation")
  }

  if(cleanup){
    if(file.exists(glue("{filename}_original"))){
      file.remove(glue("{filename}_original"))
    }
  }

}

#' Recover the source code used to create a plot.
#'
#' @param filename Path to PDF plot generated with ggsource::ggsave.
#' @param interactive If TRUE, return raw file name. If FALSE, try to use rstudioapi to open the file.
#' @importFrom glue glue
#' @importFrom rstudioapi isAvailable navigateToFile
#' @importFrom magrittr %>%
#'
#' @return Either opens the file in Rstudio or prints the path.A
#' @export
ggsource <- function(filename, interactive = T) {

  check_exiftool()

  path = system(glue("exiftool -ScriptPath {filename}"), intern = T) %>%
    strsplit(" +") %>%
    unlist %>%
    tail(n = 1)

  if(rstudioapi::isAvailable() & interactive){
    rstudioapi::navigateToFile(path)
  } else {
    return(path)
  }
}
